export const ActionTypes = {
  SET_MOVIE: "SET_MOVIE",
  SELECTED_MOVIE: "SELECTED_MOVIE",
  REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  LOGOUT: "LOGOUT",
};
